# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        AppBundle\Entity\User:
            algorithm:            bcrypt
            cost:                 13

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
       my_db:
            entity: { class: AppBundle\Entity\User, property: username }


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/admin/login$
            security: false

        main:
           provider: my_db
           pattern: ^/admin
           form_login:
             check_path: /admin/login_check
             login_path: /admin/login
             default_target_path: /admin
           logout:
             path: /admin/logout
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
