# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.user_manager:
        class: AppBundle\Manager\UserManager
        arguments: ["@doctrine.orm.entity_manager", "@security.encoder_factory", "@validator"]

    app.email_notify:
        class: AppBundle\Service\NotifyService
        lazy: true
        arguments: ["@templating", "@mailer", "@doctrine"]

    app.email_subscriber:
        class: AppBundle\EventSubscriber\EmailEventSubscriber
        arguments: ["@app.email_notify"]
        tags:
            - { name: doctrine.event_subscriber}

    app.entity_lister:
        class: AppBundle\Service\EntityListingService
        arguments: ["@doctrine.orm.entity_manager"]

    app.entity_lister_type:
        class: AppBundle\Form\EntitySelectType
        arguments: ["@app.entity_lister", "%easy_admin.entity_namespace%"]
        tags:
            - { name: form.type, alias: entity_select }